/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WorkRouteImport } from './app/work'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as CraftRouteImport } from './app/craft'
import { Route as ChecklistRouteImport } from './app/checklist'
import { Route as BookmarksDotxmlRouteImport } from './app/bookmarks[.]xml'
import { Route as BookmarksRouteImport } from './app/bookmarks'
import { Route as BlogRouteImport } from './app/blog'
import { Route as IndexRouteImport } from './app/index'
import { Route as BookmarksIndexRouteImport } from './app/bookmarks.index'
import { Route as WorkSlugRouteImport } from './app/work_.$slug'
import { Route as BookmarksSlugRouteImport } from './app/bookmarks.$slug'
import { Route as BlogSlugRouteImport } from './app/blog_.$slug'
import { Route as ApiOgIndexRouteImport } from './app/api/og/index'
import { Route as ApiErrorReportIndexRouteImport } from './app/api/error-report/index'
import { Route as ApiNarrationSlugRouteImport } from './app/api/narration/$slug'
import { Route as ApiMediaTweetVideoRouteImport } from './app/api/media/tweet-video'
import { Route as ApiBookmarksSubmitRouteImport } from './app/api/bookmarks/submit'
import { Route as ApiBookmarksRejectRouteImport } from './app/api/bookmarks/reject'
import { Route as ApiBookmarksApproveRouteImport } from './app/api/bookmarks/approve'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksDotxmlRoute = BookmarksDotxmlRouteImport.update({
  id: '/bookmarks.xml',
  path: '/bookmarks.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookmarksRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work_/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksSlugRoute = BookmarksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BookmarksRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiErrorReportIndexRoute = ApiErrorReportIndexRouteImport.update({
  id: '/api/error-report/',
  path: '/api/error-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNarrationSlugRoute = ApiNarrationSlugRouteImport.update({
  id: '/api/narration/$slug',
  path: '/api/narration/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaTweetVideoRoute = ApiMediaTweetVideoRouteImport.update({
  id: '/api/media/tweet-video',
  path: '/api/media/tweet-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksSubmitRoute = ApiBookmarksSubmitRouteImport.update({
  id: '/api/bookmarks/submit',
  path: '/api/bookmarks/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRejectRoute = ApiBookmarksRejectRouteImport.update({
  id: '/api/bookmarks/reject',
  path: '/api/bookmarks/reject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksApproveRoute = ApiBookmarksApproveRouteImport.update({
  id: '/api/bookmarks/approve',
  path: '/api/bookmarks/approve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/bookmarks': typeof BookmarksRouteWithChildren
  '/bookmarks.xml': typeof BookmarksDotxmlRoute
  '/checklist': typeof ChecklistRoute
  '/craft': typeof CraftRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bookmarks/$slug': typeof BookmarksSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/api/bookmarks/approve': typeof ApiBookmarksApproveRoute
  '/api/bookmarks/reject': typeof ApiBookmarksRejectRoute
  '/api/bookmarks/submit': typeof ApiBookmarksSubmitRoute
  '/api/media/tweet-video': typeof ApiMediaTweetVideoRoute
  '/api/narration/$slug': typeof ApiNarrationSlugRoute
  '/api/error-report/': typeof ApiErrorReportIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/bookmarks.xml': typeof BookmarksDotxmlRoute
  '/checklist': typeof ChecklistRoute
  '/craft': typeof CraftRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bookmarks/$slug': typeof BookmarksSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/api/bookmarks/approve': typeof ApiBookmarksApproveRoute
  '/api/bookmarks/reject': typeof ApiBookmarksRejectRoute
  '/api/bookmarks/submit': typeof ApiBookmarksSubmitRoute
  '/api/media/tweet-video': typeof ApiMediaTweetVideoRoute
  '/api/narration/$slug': typeof ApiNarrationSlugRoute
  '/api/error-report': typeof ApiErrorReportIndexRoute
  '/api/og': typeof ApiOgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/bookmarks': typeof BookmarksRouteWithChildren
  '/bookmarks.xml': typeof BookmarksDotxmlRoute
  '/checklist': typeof ChecklistRoute
  '/craft': typeof CraftRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/bookmarks/$slug': typeof BookmarksSlugRoute
  '/work_/$slug': typeof WorkSlugRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/api/bookmarks/approve': typeof ApiBookmarksApproveRoute
  '/api/bookmarks/reject': typeof ApiBookmarksRejectRoute
  '/api/bookmarks/submit': typeof ApiBookmarksSubmitRoute
  '/api/media/tweet-video': typeof ApiMediaTweetVideoRoute
  '/api/narration/$slug': typeof ApiNarrationSlugRoute
  '/api/error-report/': typeof ApiErrorReportIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/bookmarks'
    | '/bookmarks.xml'
    | '/checklist'
    | '/craft'
    | '/sitemap.xml'
    | '/work'
    | '/blog/$slug'
    | '/bookmarks/$slug'
    | '/work/$slug'
    | '/bookmarks/'
    | '/api/bookmarks/approve'
    | '/api/bookmarks/reject'
    | '/api/bookmarks/submit'
    | '/api/media/tweet-video'
    | '/api/narration/$slug'
    | '/api/error-report/'
    | '/api/og/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/bookmarks.xml'
    | '/checklist'
    | '/craft'
    | '/sitemap.xml'
    | '/work'
    | '/blog/$slug'
    | '/bookmarks/$slug'
    | '/work/$slug'
    | '/bookmarks'
    | '/api/bookmarks/approve'
    | '/api/bookmarks/reject'
    | '/api/bookmarks/submit'
    | '/api/media/tweet-video'
    | '/api/narration/$slug'
    | '/api/error-report'
    | '/api/og'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/bookmarks'
    | '/bookmarks.xml'
    | '/checklist'
    | '/craft'
    | '/sitemap.xml'
    | '/work'
    | '/blog_/$slug'
    | '/bookmarks/$slug'
    | '/work_/$slug'
    | '/bookmarks/'
    | '/api/bookmarks/approve'
    | '/api/bookmarks/reject'
    | '/api/bookmarks/submit'
    | '/api/media/tweet-video'
    | '/api/narration/$slug'
    | '/api/error-report/'
    | '/api/og/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  BookmarksRoute: typeof BookmarksRouteWithChildren
  BookmarksDotxmlRoute: typeof BookmarksDotxmlRoute
  ChecklistRoute: typeof ChecklistRoute
  CraftRoute: typeof CraftRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiBookmarksApproveRoute: typeof ApiBookmarksApproveRoute
  ApiBookmarksRejectRoute: typeof ApiBookmarksRejectRoute
  ApiBookmarksSubmitRoute: typeof ApiBookmarksSubmitRoute
  ApiMediaTweetVideoRoute: typeof ApiMediaTweetVideoRoute
  ApiNarrationSlugRoute: typeof ApiNarrationSlugRoute
  ApiErrorReportIndexRoute: typeof ApiErrorReportIndexRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks.xml': {
      id: '/bookmarks.xml'
      path: '/bookmarks.xml'
      fullPath: '/bookmarks.xml'
      preLoaderRoute: typeof BookmarksDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof BookmarksRoute
    }
    '/work_/$slug': {
      id: '/work_/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/$slug': {
      id: '/bookmarks/$slug'
      path: '/$slug'
      fullPath: '/bookmarks/$slug'
      preLoaderRoute: typeof BookmarksSlugRouteImport
      parentRoute: typeof BookmarksRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/error-report/': {
      id: '/api/error-report/'
      path: '/api/error-report'
      fullPath: '/api/error-report/'
      preLoaderRoute: typeof ApiErrorReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/narration/$slug': {
      id: '/api/narration/$slug'
      path: '/api/narration/$slug'
      fullPath: '/api/narration/$slug'
      preLoaderRoute: typeof ApiNarrationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/tweet-video': {
      id: '/api/media/tweet-video'
      path: '/api/media/tweet-video'
      fullPath: '/api/media/tweet-video'
      preLoaderRoute: typeof ApiMediaTweetVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/submit': {
      id: '/api/bookmarks/submit'
      path: '/api/bookmarks/submit'
      fullPath: '/api/bookmarks/submit'
      preLoaderRoute: typeof ApiBookmarksSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/reject': {
      id: '/api/bookmarks/reject'
      path: '/api/bookmarks/reject'
      fullPath: '/api/bookmarks/reject'
      preLoaderRoute: typeof ApiBookmarksRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/approve': {
      id: '/api/bookmarks/approve'
      path: '/api/bookmarks/approve'
      fullPath: '/api/bookmarks/approve'
      preLoaderRoute: typeof ApiBookmarksApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookmarksRouteChildren {
  BookmarksSlugRoute: typeof BookmarksSlugRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
}

const BookmarksRouteChildren: BookmarksRouteChildren = {
  BookmarksSlugRoute: BookmarksSlugRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
}

const BookmarksRouteWithChildren = BookmarksRoute._addFileChildren(
  BookmarksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  BookmarksRoute: BookmarksRouteWithChildren,
  BookmarksDotxmlRoute: BookmarksDotxmlRoute,
  ChecklistRoute: ChecklistRoute,
  CraftRoute: CraftRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiBookmarksApproveRoute: ApiBookmarksApproveRoute,
  ApiBookmarksRejectRoute: ApiBookmarksRejectRoute,
  ApiBookmarksSubmitRoute: ApiBookmarksSubmitRoute,
  ApiMediaTweetVideoRoute: ApiMediaTweetVideoRoute,
  ApiNarrationSlugRoute: ApiNarrationSlugRoute,
  ApiErrorReportIndexRoute: ApiErrorReportIndexRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
