/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WorkRouteImport } from './app/work'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as CraftRouteImport } from './app/craft'
import { Route as ChecklistRouteImport } from './app/checklist'
import { Route as BlogRouteImport } from './app/blog'
import { Route as IndexRouteImport } from './app/index'
import { Route as WorkSlugRouteImport } from './app/work_.$slug'
import { Route as BlogSlugRouteImport } from './app/blog_.$slug'
import { Route as ApiOgIndexRouteImport } from './app/api/og/index'
import { Route as ApiErrorReportIndexRouteImport } from './app/api/error-report/index'
import { Route as ApiNarrationSlugRouteImport } from './app/api/narration/$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work_/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiErrorReportIndexRoute = ApiErrorReportIndexRouteImport.update({
  id: '/api/error-report/',
  path: '/api/error-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNarrationSlugRoute = ApiNarrationSlugRouteImport.update({
  id: '/api/narration/$slug',
  path: '/api/narration/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/checklist': typeof ChecklistRoute
  '/craft': typeof CraftRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/narration/$slug': typeof ApiNarrationSlugRoute
  '/api/error-report/': typeof ApiErrorReportIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/checklist': typeof ChecklistRoute
  '/craft': typeof CraftRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/narration/$slug': typeof ApiNarrationSlugRoute
  '/api/error-report': typeof ApiErrorReportIndexRoute
  '/api/og': typeof ApiOgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/checklist': typeof ChecklistRoute
  '/craft': typeof CraftRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/work_/$slug': typeof WorkSlugRoute
  '/api/narration/$slug': typeof ApiNarrationSlugRoute
  '/api/error-report/': typeof ApiErrorReportIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/checklist'
    | '/craft'
    | '/sitemap.xml'
    | '/work'
    | '/blog/$slug'
    | '/work/$slug'
    | '/api/narration/$slug'
    | '/api/error-report/'
    | '/api/og/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/checklist'
    | '/craft'
    | '/sitemap.xml'
    | '/work'
    | '/blog/$slug'
    | '/work/$slug'
    | '/api/narration/$slug'
    | '/api/error-report'
    | '/api/og'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/checklist'
    | '/craft'
    | '/sitemap.xml'
    | '/work'
    | '/blog_/$slug'
    | '/work_/$slug'
    | '/api/narration/$slug'
    | '/api/error-report/'
    | '/api/og/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ChecklistRoute: typeof ChecklistRoute
  CraftRoute: typeof CraftRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiNarrationSlugRoute: typeof ApiNarrationSlugRoute
  ApiErrorReportIndexRoute: typeof ApiErrorReportIndexRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/$slug': {
      id: '/work_/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/error-report/': {
      id: '/api/error-report/'
      path: '/api/error-report'
      fullPath: '/api/error-report/'
      preLoaderRoute: typeof ApiErrorReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/narration/$slug': {
      id: '/api/narration/$slug'
      path: '/api/narration/$slug'
      fullPath: '/api/narration/$slug'
      preLoaderRoute: typeof ApiNarrationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ChecklistRoute: ChecklistRoute,
  CraftRoute: CraftRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiNarrationSlugRoute: ApiNarrationSlugRoute,
  ApiErrorReportIndexRoute: ApiErrorReportIndexRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
